
 - version: '3'
   services:
       db:
         image: mysql
         restart: always
         environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: test_db
         ports:
           - "3307:3306"
         volumes:
           - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql

       backend:
         build: ./app
         container_name: backend
         environment:
           - DB_SERVER=db
         ports:
           - 8080:8080
         links:
           - db

       frontend:
         build: ./frontend
         container_name: frontend
         ports:
           - 3000:80
         links:
           - backend


   volumes:
     data:
